@extends('home')
@section('card')
    @include('components.card')
@endsection
@section('main-left')
    @include('components.main-left')
@endsection
@section('main')
    @include('components.main')
@endsection
@section('main-right')
    @include('components.main-right')
@endsection